# Generated by Django 5.0.3 on 2024-06-16 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("dept_id", models.AutoField(primary_key=True, serialize=False)),
                ("dept_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                ("des_id", models.AutoField(primary_key=True, serialize=False)),
                ("des_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeType",
            fields=[
                ("empt_id", models.AutoField(primary_key=True, serialize=False)),
                ("empt_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("joined", models.DateField(auto_now_add=True)),
                ("status", models.CharField(max_length=20)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.department",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.designation",
                    ),
                ),
                (
                    "employee_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.employeetype",
                    ),
                ),
            ],
        ),
    ]
